server:
   port: 8888

management:
   endpoints:
      web:
         exposure:
            include: busrefresh
spring:
   profiles:
      active: native
   application:
      name: config-server
   cloud:
      config:
         server:
#            git:
#               uri: {}
#               username: {}
#               password: {}
#               clone-on-start: true
#               default-label: main
            native:
               search-locations: file:///C:/Users/Lorenzo/OneDrive/Documentos/microservice-course/config-service-repository