server:
   port: 8082

spring:
   application:
      name: api-gateway-service
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
            - id: users-service
              uri: lb://user-service
              predicates:
                 - Path=/user-service/users
                 - Method=POST
              filtes:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - id: users-service-h2-console
              uri: lb://user-service/h2-console
              predicates:
                 - Path=/user-service/h2-console
                 - Method=GET
              filtes:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - id: users-service-login
              uri: lb://user-service
              predicates:
                 - Path=/user-service/users/login
                 - Method=POST
              filtes:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka